### ISSUE TITLE
Support default app domain for vs adapter

### ISSUE THREAD

**Issue by ptrupti** [nunit-legacy/nunitv2#52] opened 2018-06-20 00:15 UTC
Hi,
We use the nunit vs adapter version 2.6.4 to test our application. We recently added CEFSharp component to our application which creates a subprocess in the default app domain. This is causing a crash when running tests because the adapter creates a new app domain per test dll. 
Would appreciate any pointers on how to enable support for this by updating the adapter code.

Thanks,
Trupti.

**Comment by CharliePoole** [comment] 2018-06-20 01:51
If you are having a problem with NUnit V2, which includes the framework, console runner and GUI, this is the place. Since the NUnit Project no longer maintains NUnit V2, I have taken this on with two releases so far... 2.6.5 and 2.6.6.

However, it sounds as if you have a problem with the NUnit Visual Studio Test Adapter, which is separate from NUnit itself and is still maintained by the NUnit Project.

At this point, I suggest you try to verify the existence of the same problem when running your tests with the NUnit 2.6.4 console runner. IF the same problem exists, then we can discuss it further here. Otherwise, you need to file an issue at https://github.com/nunit/nunit-vs-adapter

**Comment by CharliePoole** [comment] 2018-06-28 23:35
Closing this as apparently not a bug in nunit itself, since no more info has been received. Feel free to post here if you do have further information and we can re-open it.

**Closed by CharliePoole** 2018-06-28 23:35 UTC
Labels: notabug
