### ISSUE TITLE
NUnit console does not exit automatically after all unit tests passed at the end.

### ISSUE THREAD

**Issue by gustavocalheiros** [nunit-legacy/nunitv2#79] opened 2020-04-24 08:58 UTC
Hello, I'm having the exact same problem described by the user here:
https://github.com/nunit/nunit-console/issues/429

![image](https://user-images.githubusercontent.com/4106594/80196049-16a05000-861d-11ea-92af-ee045927725c.png)

```
24-Apr-2020 09:24:53 | Runtime Environment 
24-Apr-2020 09:24:53 | OS Version: Microsoft Windows NT 6.2.9200.0
24-Apr-2020 09:24:53 | CLR Version: 2.0.50727.9043 ( Net 3.5 )
24-Apr-2020 09:24:53 |  
24-Apr-2020 09:24:53 | ProcessModel: Default    DomainUsage: Single
24-Apr-2020 09:24:53 | Execution Runtime: net-3.5
24-Apr-2020 09:36:47 |  
24-Apr-2020 09:36:47 | Tests run: 14, Errors: 0, Failures: 0, Inconclusive: 0, Time: 713.5300136 seconds
24-Apr-2020 09:36:47 | Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
24-Apr-2020 09:36:47 |  
24-Apr-2020 11:08:20 | BodyExecutionEnd:
24-Apr-2020 11:08:20 | Body Execution Finished
```

Pay attention that the job takes normally 10 minutes. it has ended at 09:36 and it was hung since this time. once I killed manually the "nUnit-Agent" task (at 11:08), it could finally finish its execution. this happens more or less one time for every 10 runs.

the task is run via MSBuild < Exec > with a timeout of 30 minutes, that BTW does not work on this case.

I'm using latest 2.7.1 version.

**Comment by CharliePoole** [comment] 2020-04-24 11:42
@gustavocalheiros Are you using 2.7.1 for both the framework and the console runner? What is the exact command-line you use? Does this happen for all tests or just specific tests of yours?

**Comment by gustavocalheiros** [comment] 2020-04-24 11:50
1- 2.7.1 is the only package that I have.
2- 

```
24-Apr-2020 09:24:53 |  
..\..\externals\NUnit\nunit-console.exe /noshadow /labels /err=../../Reports/BodyResults.errors.txt /out=../../Reports/BodyResults.txt /xml=../../Reports/BodyResults.xml ..\..\bin\Release\BodyTests.dll

24-Apr-2020 09:24:53 | NUnit-Console version 2.7.1.0
-- | --
24-Apr-2020 09:24:53 | Copyright (C) 2002-2014, 2018 Charlie Poole.
24-Apr-2020 09:24:53 | Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
24-Apr-2020 09:24:53 | Copyright (C) 2000-2002 Philip Craig.
24-Apr-2020 09:24:53 | All Rights Reserved.
```




3- It can  be reproduced in any test execution, not only on this specific run;

BTW, I'm using windows 10 1809.

**Comment by CharliePoole** [comment] 2021-05-01 19:38
Closing this as not-reproducible. My guess is that it's due to some issue related to threading within your own project.

**Closed by CharliePoole** 2021-05-01 19:38 UTC
